### ISSUE TITLE
Update to version 1.4

### ISSUE THREAD

**Issue by psafarov** [mariadb-corporation/mariadb-community-columnstore-docker#1]
Do you have plans to update this image to version 1.4? 1.2 has some memory leaks, so it would be really nice to upgrade

**Comment by drrtuy** [comment]
Greetings.
ColumnStore 1.4 is available for Enterprise customers only. 
So we will upgrade docker image with 1.2.6 and later with 1.5 release that is going to happen this May.
Could you ellaborate on the memory leaks? What are the daemons that leaks? Do you have test cases to reproduce?

**Comment by psafarov** [comment]
Leaks happen to WriteEngineServ and DMLProc, it is noticeable during periods of many writes to columnstore table. I thought lowering SystemConfig.MemoryCheckPercent would help, but it didn't, only restart of these processes frees occupied memory, otherwise our server simply goes down.

**Comment by drrtuy** [comment]
This looks like either a problem we solved in 1.2.3 replacing default memory allocator with jemalloc or a syscat connection specific buffer memory leak. Can you double check if /proc/$(pidof WriteEngineServ)/maps | grep jemalloc outputs something.
I bet you insert the data using INSERT and not cpimport?

**Comment by drrtuy** [comment]
I suggest you to open a bug in our [bugtracker](https://jira.mariadb.org).

**Comment by psafarov** [comment]
@drrtuy  I got around this issue by just writing data with a non transactional statement, hence I can't help with your last request without putting the server in the unsafe state again. I really like the work you do with this project. Thank you for your help.
