### ISSUE TITLE
S3 Not compatible with Minio

### ISSUE THREAD

**Issue by bbarclay** [mariadb-corporation/mariadb-community-columnstore-docker#10]
I've tried everything under the sun to get Minio to configure with it's S3 compatability. For some reason it's the same error no matter what I've tried, and I've tried a lot. 

Apr  4 00:42:12 a6e510431faf StorageManager[48]: S3Storage::putObject(): failed to PUT, server says 'Couldn't resolve host name'.  bucket = columnstorage, key = xxxxxxxxxxxxxxxxxxxxxxx. connectivity_test.  Retrying...

Any idea how to get this configure with s3 that is not AWS? Perhaps, how to get it to configure to Minio?

**Comment by drrtuy** [comment]
IIRC the problem comes from the endpoint URI used in the configuration file. MinIO uses http instead of https. AFAIK there are some prod installations that leverages MinIO.

**Comment by drrtuy** [comment]
Something looks wrong in your instllation. I suggest you to ask questions regarding generic usage of MCS in the corresponding [Google group](https://groups.google.com/g/mariadb-columnstore).
