### ISSUE TITLE
Importing data throws lots of errors

### ISSUE THREAD

**Issue by bbarclay** [mariadb-corporation/mariadb-community-columnstore-docker#12]
I'm guessing these are simular to the replication errors that kill the repliction server.

MySQL Error 1030 (HY000): Got error -1 "Internal error < 0 (Not system error)" from storage engine Columnstore @ file bytes range [0, 50000077): LOAD DATA LOCAL INFILE

**Comment by drrtuy** [comment]
There might be different reasons for this. You can find more info in /var/log/mariadb/columnstore/ files.

**Comment by drrtuy** [comment]
Something looks wrong in your instllation. I suggest you to ask questions regarding generic usage of MCS in the corresponding [Google group](https://groups.google.com/g/mariadb-columnstore).
