### ISSUE TITLE
Window functions over large data sets are terribly slow. 

### ISSUE THREAD

**Issue by bbarclay** [mariadb-corporation/mariadb-community-columnstore-docker#13]
Window Functions are terribly slow. I tried a window function with over 50 million rows. Without specifying a where clause, the transaction never resolves. When doing just a generic sum clause, it seems really fast. But no nowhere what you would expect from an analytics engine that is processing a Windows function to calculate over 50 million rows of data.

**Comment by drrtuy** [comment]
Something looks wrong in your instllation. I suggest you to ask questions regarding generic usage of MCS in the corresponding [Google group](https://groups.google.com/g/mariadb-columnstore).
