### ISSUE TITLE
How do I use this container in a docker-compose setup?

### ISSUE THREAD

**Issue by pofl** [mariadb-corporation/mariadb-community-columnstore-docker#3]
Is there some default user/pw credentials? I want to connect to this container from an application running in another container.

The official docker mariadb image is quite convenient in this regard. There I can define a user+pw via env vars.

**Comment by pofl** [comment]
To answer this question myself:
It's currently not possible. Steps to get a newly-created-from-this-image container to a usable state:
1. `$ docker run -p 3306:3306 --name mariacol mariadb/columnstore` to create and start a new container
2. `$ docker exec -it mariacol mariadb` to run the mariadb shell from inside the container
3. Run `GRANT ALL PRIVILEGES ON *.* TO '<username>'@'%' IDENTIFIED BY '<password>';`

Now you can connect to this container from the outside with these credentials

**Comment by jonbaldie** [comment]
This is a very helpful note thanks. Why haven't the project admins got round to reviewing/merging this yet?
