### ISSUE TITLE
access to cpimport

### ISSUE THREAD

**Issue by samstiyer** [mariadb-corporation/mariadb-community-columnstore-docker#9]
Hi,

Just checking how to call cpimport within the columnstore container!

Thanks!

**Comment by drrtuy** [comment]
@samstiyer The same way as for a non-container installation. [This doc](https://mariadb.com/docs/multi-node/columnstore/operations/load-data/cpimport/) has cpimport ref.

**Comment by drrtuy** [comment]
I suggest you to ask questions about container usage in https://mariadb.zulipchat.com/ in future.
